version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: lusm123
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: documents
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./config/posts.csv:/var/lib/postgresql/data/posts.csv
      - ./.docker/postgres/setup.sql:/docker-entrypoint-initdb.d/init.sql
