version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    container_name: tse_postgres
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: lusm123
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: documents
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./config/posts.csv:/var/lib/postgresql/data/posts.csv
      - ./.docker/postgres/setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - share-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: tse_elasticsearch
    environment:
      - node.name=documents-es
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - share-network

  logstash:
    #image: docker.elastic.co/logstash/logstash:7.14.1
    image: docker.elastic.co/logstash/logstash:7.14.1@sha256:eb2d60ba01e4aabb28001bf1b17ba69f6c5039746103e004d519f433ab5d584c
    container_name: tse_logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 5044:5044
    volumes:
      - ./.docker/logstash/postgresql-jdbc.jar:/usr/share/logstash/logstash-core/lib/jars/postgresql-jdbc.jar
      - ./.docker/logstash/postgres-jdbc-input.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - share-network
    depends_on:
      - elasticsearch

networks:
  share-network:
    driver: bridge

volumes:
  esdata:
  pgdata:
