version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: lusm123
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: documents
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./config/posts.csv:/var/lib/postgresql/data/posts.csv
      - ./.docker/postgres/setup.sql:/docker-entrypoint-initdb.d/init.sql
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - node.name=documents-es
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    

